# Generated by Django 2.2.28 on 2024-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240422_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='type_name',
            field=models.CharField(choices=[('number', 'Число'), ('text', 'Строка'), ('string', 'Текст'), ('date', 'Дата'), ('week', 'Неделя'), ('datetime-local', 'Дата и время'), ('time', 'Время'), ('email', 'Электронная почта'), ('file', 'Файл'), ('image', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('checkbox', 'Чекбокс'), ('url', 'Ссылка'), ('tel', 'Телефон')], default='text', max_length=250, unique=True, verbose_name='Тип атрибута (text, integer, file...)'),
        ),
    ]
