# Generated by Django 2.2.28 on 2024-05-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0003_auto_20240422_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200, null=True)),
                ('action_type', models.CharField(choices=[('Создание', 'Создание'), ('Чтение', 'Чтение'), ('Редактирование', 'Редактирование'), ('Удаление', 'Удаление'), ('Вход', 'Вход'), ('Выход', 'Выход'), ('Ошибка входа', 'Ошибка входа')], max_length=15)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Успешный', 'Успешный'), ('Неудачный', 'Неудачный')], default='Успешный', max_length=7)),
                ('ip', models.GenericIPAddressField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'лог',
                'ordering': ('action_time',),
                'verbose_name_plural': 'Журнал логов',
            },
        ),
    ]
