# Generated by Django 4.2.7 on 2023-12-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True, verbose_name='Имя поля')),
                ('label', models.CharField(max_length=100, verbose_name='Название поля (label)')),
                ('help_text', models.CharField(max_length=100, verbose_name='Текст подсказка (help_text)')),
                ('is_uniq', models.BooleanField(default=False, verbose_name='Уникальность поля')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Тип атрибута (forms.fields)')),
            ],
            options={
                'verbose_name': 'тип атрибута',
                'verbose_name_plural': 'Типы атрибутов',
                'ordering': ('type_name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_cards.attribute', verbose_name='Атрибут')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'default_related_name': 'card_attrs',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='attr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='new_cards.attributetype', verbose_name='Тип атрибута (поля)'),
        ),
    ]
