# Generated by Django 4.2.7 on 2023-12-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=250, unique=True, verbose_name='Имя поля')),
                ('label', models.CharField(max_length=250, unique=True, verbose_name='Название поля (label)')),
                ('help_text', models.CharField(max_length=250, verbose_name='Текст подсказка (help_text)')),
                ('is_uniq', models.BooleanField(default=False, verbose_name='Уникальность поля')),
            ],
            options={
                'verbose_name': 'тип атрибута',
                'verbose_name_plural': 'Типы атрибутов',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст')),
                ('integer', models.IntegerField(blank=True, null=True, verbose_name='Число')),
                ('image', models.ImageField(blank=True, null=True, upload_to='new_cards/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text__isnull', True), ('integer__isnull', False), ('image__isnull', False)), models.Q(('text__isnull', False), ('integer__isnull', True), ('image__isnull', False)), models.Q(('text__isnull', False), ('integer__isnull', False), ('image__isnull', True)), _connector='OR'), name='only_one_value'),
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='new_cards.attribute', verbose_name='Атрибут'),
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='new_cards.card', verbose_name='Карточка'),
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='new_cards.value', verbose_name='Значение'),
        ),
    ]
