# Generated by Django 4.2.8 on 2023-12-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='field_name',
            field=models.SlugField(unique=True, verbose_name='Имя поля'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='type_name',
            field=models.SlugField(unique=True, verbose_name='Тип атрибута (text, integer, file...)'),
        ),
    ]
