# Generated by Django 4.2.8 on 2023-12-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_cards', '0002_alter_attribute_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
