# Generated by Django 4.2.7 on 2023-11-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Имя поля')),
                ('label', models.CharField(max_length=100, verbose_name='Название поля (label)')),
                ('help_text', models.CharField(max_length=100, verbose_name='Текст подсказка (help_text)')),
            ],
            options={
                'verbose_name': 'атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_type', models.CharField(max_length=100, verbose_name='Тип атрибута (forms.fields)')),
            ],
            options={
                'verbose_name': 'тип атрибута',
                'verbose_name_plural': 'Типы атрибутов',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
                ('id_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.attribute', verbose_name='Атрибут')),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='attr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='cards.attributetype', verbose_name='Тип атрибута (поля)'),
        ),
    ]
