# Generated by Django 4.2.7 on 2023-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_attribute_attributetype_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_uniq',
            field=models.BooleanField(default=False, verbose_name='Уникальность поля'),
        ),
    ]
