# Generated by Django 4.2.7 on 2023-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_attribute_is_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='field_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя поля'),
        ),
    ]
